"""Scene definitions for the RUAI demo video.

Each scene has narration text (for TTS) and a target approximate duration.
The narration drives the actual timing — the recording script pads UI actions
to match the audio length per scene.
"""

SCENES = [
    {
        "id": "01_hook",
        "narration": (
            "Hi, I'm an R.U.A.I. reviewer. I see every A.I. use case the company wants to build. "
            "Last quarter, that meant reading forty-page submissions cold, hunting for the risky bits. "
            "Today, the dashboard does the heavy lifting. Let me show you my morning."
        ),
    },
    {
        "id": "02_dashboard",
        "narration": (
            "Five tiles tell me where everything stands. "
            "What's waiting on me, what's with the submitter, what's closed. "
            "I filter to Needs Review, sort by aging, and I know exactly where to start. "
            "The risk badge on each row is generated by A.I. the moment a submission comes in. "
            "So even before I click, I know which ones deserve my Monday morning."
        ),
    },
    {
        "id": "03_ai_first_pass",
        "narration": (
            "Here's where the real time savings live. "
            "The moment a use case lands, our language model reads the full form, "
            "the uploaded design docs, and our policy library. "
            "It produces a first-pass review with an overall risk score, "
            "a breakdown across data, model, and deployment dimensions, "
            "and specific concerns flagged with citations back to the source text. "
            "What used to take me forty-five minutes of reading and note-taking "
            "is sitting here, structured and ready, when I open the ticket."
        ),
    },
    {
        "id": "04_rerun_compare",
        "narration": (
            "Sometimes the first pass misses nuance. "
            "Maybe the submitter clarified something, or I want to test a stricter prompt. "
            "One click re-runs the review, and the Compare button stacks every version side by side. "
            "I can see exactly where the A.I. changed its mind and why. "
            "A second opinion, on demand, in under a minute."
        ),
    },
    {
        "id": "05_chat",
        "narration": (
            "If I have a specific question, "
            "was P.I.I. discussed anywhere, did they commit to a human in the loop, "
            "I just ask. "
            "The chat is grounded in the submission and the reference docs, "
            "so I get cited answers instead of hunting through P.D.F.s. "
            "This is the feature I didn't know I needed until I had it."
        ),
    },
    {
        "id": "06_prompts",
        "narration": (
            "And the prompts driving all this aren't buried in code. "
            "They live here, fully versioned. "
            "When policy changes, I edit the review prompt, preview it against a real submission, "
            "and publish a new version. "
            "Old reviews stay tied to the prompt that generated them, so the audit trail is intact."
        ),
    },
    {
        "id": "07_docs",
        "narration": (
            "Reference docs, our A.I. policy, the risk taxonomy, regulatory guidance, "
            "feed every review and every chat answer. "
            "Drop a new P.D.F. in here, it's indexed, and the next review uses it automatically. "
            "No code changes, no waiting on engineering."
        ),
    },
    {
        "id": "08_analytics",
        "narration": (
            "Approve, reject, or request changes. One click, with canned templates for the common asks. "
            "P.D.F. export for the audit trail. "
            "And the analytics panel shows me approval rates, review times, and where the bottlenecks are. "
            "So I can have data-backed conversations with my manager."
        ),
    },
    {
        "id": "09_payoff",
        "narration": (
            "Same queue, a fraction of the time. "
            "I spend my hours on the calls that actually need human judgment, "
            "not on extracting facts a model can pull in seconds. "
            "That's responsible use of A.I., applied to the team that polices it."
        ),
    },
]
